"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.AccountIntegration = void 0;
var AccountIntegration = /** @class */ (function () {
    function AccountIntegration() {
    }
    AccountIntegration.getAttributeTypeMap = function () {
        return AccountIntegration.attributeTypeMap;
    };
    AccountIntegration.discriminator = undefined;
    AccountIntegration.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<AccountIntegration.CategoriesEnum>"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "square_image",
            "baseName": "square_image",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        }
    ];
    return AccountIntegration;
}());
exports.AccountIntegration = AccountIntegration;
(function (AccountIntegration) {
    var CategoriesEnum;
    (function (CategoriesEnum) {
        CategoriesEnum[CategoriesEnum["Hris"] = 'hris'] = "Hris";
        CategoriesEnum[CategoriesEnum["Ats"] = 'ats'] = "Ats";
        CategoriesEnum[CategoriesEnum["Accounting"] = 'accounting'] = "Accounting";
    })(CategoriesEnum = AccountIntegration.CategoriesEnum || (AccountIntegration.CategoriesEnum = {}));
})(AccountIntegration = exports.AccountIntegration || (exports.AccountIntegration = {}));
exports.AccountIntegration = AccountIntegration;
