"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.BenefitPlanTypeEnum = void 0;
var BenefitPlanTypeEnum;
(function (BenefitPlanTypeEnum) {
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Medical"] = 'MEDICAL'] = "Medical";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Dental"] = 'DENTAL'] = "Dental";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Vision"] = 'VISION'] = "Vision";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Hsa"] = 'HSA'] = "Hsa";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["FsaMedical"] = 'FSA_MEDICAL'] = "FsaMedical";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["FsaDependentCare"] = 'FSA_DEPENDENT_CARE'] = "FsaDependentCare";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["SimpleIra"] = 'SIMPLE_IRA'] = "SimpleIra";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["_401K"] = '_401K'] = "_401K";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Roth401K"] = 'ROTH_401K'] = "Roth401K";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["OtherNonTaxable"] = 'OTHER_NON_TAXABLE'] = "OtherNonTaxable";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["CommuterTransit"] = 'COMMUTER_TRANSIT'] = "CommuterTransit";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["CommuterParking"] = 'COMMUTER_PARKING'] = "CommuterParking";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["_401KLoanPayment"] = '_401K_LOAN_PAYMENT'] = "_401KLoanPayment";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["ShortDisability"] = 'SHORT_DISABILITY'] = "ShortDisability";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["LongDisability"] = 'LONG_DISABILITY'] = "LongDisability";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Life"] = 'LIFE'] = "Life";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["SepIra"] = 'SEP_IRA'] = "SepIra";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Sarsep"] = 'SARSEP'] = "Sarsep";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["CustomTaxable"] = 'CUSTOM_TAXABLE'] = "CustomTaxable";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["_403B"] = '_403B'] = "_403B";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["Roth403B"] = 'ROTH_403B'] = "Roth403B";
    BenefitPlanTypeEnum[BenefitPlanTypeEnum["StudentLoan"] = 'STUDENT_LOAN'] = "StudentLoan";
})(BenefitPlanTypeEnum = exports.BenefitPlanTypeEnum || (exports.BenefitPlanTypeEnum = {}));
