/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BenefitPlanTypeEnum {
    Medical = <any> 'MEDICAL',
    Dental = <any> 'DENTAL',
    Vision = <any> 'VISION',
    Hsa = <any> 'HSA',
    FsaMedical = <any> 'FSA_MEDICAL',
    FsaDependentCare = <any> 'FSA_DEPENDENT_CARE',
    SimpleIra = <any> 'SIMPLE_IRA',
    _401K = <any> '_401K',
    Roth401K = <any> 'ROTH_401K',
    OtherNonTaxable = <any> 'OTHER_NON_TAXABLE',
    CommuterTransit = <any> 'COMMUTER_TRANSIT',
    CommuterParking = <any> 'COMMUTER_PARKING',
    _401KLoanPayment = <any> '_401K_LOAN_PAYMENT',
    ShortDisability = <any> 'SHORT_DISABILITY',
    LongDisability = <any> 'LONG_DISABILITY',
    Life = <any> 'LIFE',
    SepIra = <any> 'SEP_IRA',
    Sarsep = <any> 'SARSEP',
    CustomTaxable = <any> 'CUSTOM_TAXABLE',
    _403B = <any> '_403B',
    Roth403B = <any> 'ROTH_403B',
    StudentLoan = <any> 'STUDENT_LOAN'
}
