/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RequestTypeEnum } from './requestTypeEnum';
import { TimeOffStatusEnum } from './timeOffStatusEnum';
import { UnitsEnum } from './unitsEnum';

/**
* # The TimeOff Object ### Description The `TimeOff` object is used to represent a Time Off Request filed by an employee.
*/
export class CreateTimeOff {
    /**
    * The employee requesting time off.
    */
    'employee'?: string | null;
    /**
    * The employee approving the time off request.
    */
    'approver'?: string | null;
    /**
    * The status of this time off request.
    */
    'status'?: TimeOffStatusEnum | null;
    /**
    * The status of this time off request.
    */
    'employeeNote'?: string | null;
    /**
    * The unit of time requested.
    */
    'units'?: UnitsEnum | null;
    /**
    * The number of time off units requested.
    */
    'amount'?: number | null;
    /**
    * The type of time off request.
    */
    'requestType'?: RequestTypeEnum | null;
    'startDate'?: Date;
    'endDate'?: Date;
    'leaveTypeId'?: string;
    'timeOffPolicyId'?: string;
    'partOfDay'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employee",
            "baseName": "employee",
            "type": "string"
        },
        {
            "name": "approver",
            "baseName": "approver",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TimeOffStatusEnum"
        },
        {
            "name": "employeeNote",
            "baseName": "employee_note",
            "type": "string"
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "UnitsEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "requestType",
            "baseName": "request_type",
            "type": "RequestTypeEnum"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "Date"
        },
        {
            "name": "leaveTypeId",
            "baseName": "leave_type_id",
            "type": "string"
        },
        {
            "name": "timeOffPolicyId",
            "baseName": "time_off_policy_id",
            "type": "string"
        },
        {
            "name": "partOfDay",
            "baseName": "part_of_day",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateTimeOff.attributeTypeMap;
    }
}

