"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataPassthroughRequest = void 0;
/**
* # The DataPassthrough Object ### Description The `DataPassthrough` object is used to send information to an otherwise-unsupported third-party endpoint.  ### Usage Example Create a `DataPassthrough` to get team hierarchies from your Rippling integration.
*/
var DataPassthroughRequest = /** @class */ (function () {
    function DataPassthroughRequest() {
    }
    DataPassthroughRequest.getAttributeTypeMap = function () {
        return DataPassthroughRequest.attributeTypeMap;
    };
    DataPassthroughRequest.discriminator = undefined;
    DataPassthroughRequest.attributeTypeMap = [
        {
            "name": "method",
            "baseName": "method",
            "type": "MethodEnum"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "base_url_override",
            "baseName": "base_url_override",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: any; }"
        }
    ];
    return DataPassthroughRequest;
}());
exports.DataPassthroughRequest = DataPassthroughRequest;
