/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* # The Deduction Object ### Description The `Deduction` object is used to represent a deduction for a given employee\'s payroll run. One run could include several deductions.  ### Usage Example Fetch from the `LIST Deductions` endpoint and filter by `ID` to show all deductions.
*/
export class Deduction {
    'id'?: string;
    /**
    * The deduction\'s employee payroll run.
    */
    'employeePayrollRun'?: string | null;
    /**
    * The deduction\'s name.
    */
    'name'?: string | null;
    /**
    * The amount the employee is deducting.
    */
    'employeeDeduction'?: number | null;
    /**
    * The amount the company is deducting.
    */
    'companyDeduction'?: number | null;
    'remoteData'?: Array<{ [key: string]: any; }> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "employeePayrollRun",
            "baseName": "employee_payroll_run",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "employeeDeduction",
            "baseName": "employee_deduction",
            "type": "number"
        },
        {
            "name": "companyDeduction",
            "baseName": "company_deduction",
            "type": "number"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<{ [key: string]: any; }>"
        }    ];

    static getAttributeTypeMap() {
        return Deduction.attributeTypeMap;
    }
}

