/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmploymentStatusEnum } from './employmentStatusEnum';
import { EthnicityEnum } from './ethnicityEnum';
import { GenderEnum } from './genderEnum';
import { MaritalStatusEnum } from './maritalStatusEnum';
import { RemoteData } from './remoteData';

/**
* # The Employee Object ### Description The `Employee` object is used to represent an Employee for a company.  ### Usage Example Fetch from the `LIST Employee` endpoint and filter by `ID` to show all employees.
*/
export class Employee {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remoteId'?: string | null;
    /**
    * The employee\'s number that appears in the remote UI. Note: This is distinct from the remote_id field, which is a unique identifier for the employee set by the remote API, and is not exposed to the user.
    */
    'employeeNumber'?: string | null;
    /**
    * The ID of the employee\'s company.
    */
    'company'?: string | null;
    /**
    * The employee\'s first name.
    */
    'firstName'?: string | null;
    /**
    * The employee\'s last name.
    */
    'lastName'?: string | null;
    /**
    * The employee\'s full name, to use for display purposes.
    */
    'displayFullName'?: string | null;
    /**
    * The employee\'s work email.
    */
    'workEmail'?: string | null;
    /**
    * The employee\'s personal email.
    */
    'personalEmail'?: string | null;
    /**
    * The employee\'s mobile phone number.
    */
    'mobilePhoneNumber'?: string | null;
    /**
    * Array of `Employment` IDs for this Employee.
    */
    'employments'?: Array<string>;
    /**
    * The employee\'s home address.
    */
    'homeLocation'?: string | null;
    /**
    * The employee\'s work address.
    */
    'workLocation'?: string | null;
    /**
    * The employee ID of the employee\'s manager.
    */
    'manager'?: string | null;
    /**
    * The employee\'s team.
    */
    'team'?: string | null;
    /**
    * The employee\'s pay group
    */
    'payGroup'?: string | null;
    /**
    * The employee\'s social security number.
    */
    'ssn'?: string | null;
    /**
    * The employee\'s gender.
    */
    'gender'?: GenderEnum | null;
    /**
    * The employee\'s ethnicity.
    */
    'ethnicity'?: EthnicityEnum | null;
    /**
    * The employee\'s marital status.
    */
    'maritalStatus'?: MaritalStatusEnum | null;
    /**
    * The employee\'s date of birth.
    */
    'dateOfBirth'?: Date | null;
    /**
    * The date that the employee was hired, usually the day that an offer letter is signed. If an employee has multiple hire dates from previous employments, this represents the most recent hire date. Note: If you\'re looking for the employee\'s start date, refer to the start_date field.
    */
    'hireDate'?: Date | null;
    /**
    * The date that the employee started working. If an employee has multiple start dates from previous employments, this represents the most recent start date.
    */
    'startDate'?: Date | null;
    /**
    * The employment status of the employee.
    */
    'employmentStatus'?: EmploymentStatusEnum | null;
    /**
    * The employee\'s termination date.
    */
    'terminationDate'?: Date | null;
    /**
    * The URL of the employee\'s avatar image.
    */
    'avatar'?: string | null;
    'remoteData'?: Array<RemoteData> | null;
    /**
    * Custom fields configured for a given model.
    */
    'customFields'?: { [key: string]: any; } | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remoteId",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "employeeNumber",
            "baseName": "employee_number",
            "type": "string"
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "displayFullName",
            "baseName": "display_full_name",
            "type": "string"
        },
        {
            "name": "workEmail",
            "baseName": "work_email",
            "type": "string"
        },
        {
            "name": "personalEmail",
            "baseName": "personal_email",
            "type": "string"
        },
        {
            "name": "mobilePhoneNumber",
            "baseName": "mobile_phone_number",
            "type": "string"
        },
        {
            "name": "employments",
            "baseName": "employments",
            "type": "Array<string>"
        },
        {
            "name": "homeLocation",
            "baseName": "home_location",
            "type": "string"
        },
        {
            "name": "workLocation",
            "baseName": "work_location",
            "type": "string"
        },
        {
            "name": "manager",
            "baseName": "manager",
            "type": "string"
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "string"
        },
        {
            "name": "payGroup",
            "baseName": "pay_group",
            "type": "string"
        },
        {
            "name": "ssn",
            "baseName": "ssn",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "GenderEnum"
        },
        {
            "name": "ethnicity",
            "baseName": "ethnicity",
            "type": "EthnicityEnum"
        },
        {
            "name": "maritalStatus",
            "baseName": "marital_status",
            "type": "MaritalStatusEnum"
        },
        {
            "name": "dateOfBirth",
            "baseName": "date_of_birth",
            "type": "Date"
        },
        {
            "name": "hireDate",
            "baseName": "hire_date",
            "type": "Date"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "employmentStatus",
            "baseName": "employment_status",
            "type": "EmploymentStatusEnum"
        },
        {
            "name": "terminationDate",
            "baseName": "termination_date",
            "type": "Date"
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return Employee.attributeTypeMap;
    }
}

