"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.EmploymentStatusEnum = void 0;
var EmploymentStatusEnum;
(function (EmploymentStatusEnum) {
    EmploymentStatusEnum[EmploymentStatusEnum["Active"] = 'ACTIVE'] = "Active";
    EmploymentStatusEnum[EmploymentStatusEnum["Pending"] = 'PENDING'] = "Pending";
    EmploymentStatusEnum[EmploymentStatusEnum["Inactive"] = 'INACTIVE'] = "Inactive";
})(EmploymentStatusEnum = exports.EmploymentStatusEnum || (exports.EmploymentStatusEnum = {}));
