"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.EmploymentTypeEnum = void 0;
var EmploymentTypeEnum;
(function (EmploymentTypeEnum) {
    EmploymentTypeEnum[EmploymentTypeEnum["FullTime"] = 'FULL_TIME'] = "FullTime";
    EmploymentTypeEnum[EmploymentTypeEnum["PartTime"] = 'PART_TIME'] = "PartTime";
    EmploymentTypeEnum[EmploymentTypeEnum["Intern"] = 'INTERN'] = "Intern";
    EmploymentTypeEnum[EmploymentTypeEnum["Contractor"] = 'CONTRACTOR'] = "Contractor";
    EmploymentTypeEnum[EmploymentTypeEnum["Freelance"] = 'FREELANCE'] = "Freelance";
})(EmploymentTypeEnum = exports.EmploymentTypeEnum || (exports.EmploymentTypeEnum = {}));
