/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmploymentTypeEnum } from './employmentTypeEnum';
import { FlsaStatusEnum } from './flsaStatusEnum';
import { PayCurrencyEnum } from './payCurrencyEnum';
import { PayFrequencyEnum } from './payFrequencyEnum';
import { PayPeriodEnum } from './payPeriodEnum';
import { RemoteData } from './remoteData';

/**
* # The Employment Object ### Description The `Employment` object is used to represent an employment position at a company. These are associated with the employee filling the role.  ### Usage Example Fetch from the `LIST Employments` endpoint and filter by `ID` to show all employees.
*/
export class Employment {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remoteId'?: string | null;
    /**
    * The position\'s title.
    */
    'jobTitle'?: string | null;
    /**
    * The position\'s pay rate in dollars.
    */
    'payRate'?: number | null;
    /**
    * The time period this pay rate encompasses.
    */
    'payPeriod'?: PayPeriodEnum | null;
    /**
    * The position\'s pay frequency.
    */
    'payFrequency'?: PayFrequencyEnum | null;
    /**
    * The position\'s currency code.
    */
    'payCurrency'?: PayCurrencyEnum | null;
    /**
    * The position\'s FLSA status.
    */
    'flsaStatus'?: FlsaStatusEnum | null;
    /**
    * The position\'s effective date.
    */
    'effectiveDate'?: Date | null;
    /**
    * The position\'s type of employment.
    */
    'employmentType'?: EmploymentTypeEnum | null;
    'remoteData'?: Array<RemoteData> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remoteId",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "jobTitle",
            "baseName": "job_title",
            "type": "string"
        },
        {
            "name": "payRate",
            "baseName": "pay_rate",
            "type": "number"
        },
        {
            "name": "payPeriod",
            "baseName": "pay_period",
            "type": "PayPeriodEnum"
        },
        {
            "name": "payFrequency",
            "baseName": "pay_frequency",
            "type": "PayFrequencyEnum"
        },
        {
            "name": "payCurrency",
            "baseName": "pay_currency",
            "type": "PayCurrencyEnum"
        },
        {
            "name": "flsaStatus",
            "baseName": "flsa_status",
            "type": "FlsaStatusEnum"
        },
        {
            "name": "effectiveDate",
            "baseName": "effective_date",
            "type": "Date"
        },
        {
            "name": "employmentType",
            "baseName": "employment_type",
            "type": "EmploymentTypeEnum"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        }    ];

    static getAttributeTypeMap() {
        return Employment.attributeTypeMap;
    }
}

