"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.EndUserDetailsRequest = void 0;
var EndUserDetailsRequest = /** @class */ (function () {
    function EndUserDetailsRequest() {
    }
    EndUserDetailsRequest.getAttributeTypeMap = function () {
        return EndUserDetailsRequest.attributeTypeMap;
    };
    EndUserDetailsRequest.discriminator = undefined;
    EndUserDetailsRequest.attributeTypeMap = [
        {
            "name": "end_user_email_address",
            "baseName": "end_user_email_address",
            "type": "string"
        },
        {
            "name": "end_user_organization_name",
            "baseName": "end_user_organization_name",
            "type": "string"
        },
        {
            "name": "end_user_origin_id",
            "baseName": "end_user_origin_id",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<EndUserDetailsRequest.CategoriesEnum>"
        },
        {
            "name": "integration",
            "baseName": "integration",
            "type": "string"
        }
    ];
    return EndUserDetailsRequest;
}());
exports.EndUserDetailsRequest = EndUserDetailsRequest;
(function (EndUserDetailsRequest) {
    var CategoriesEnum;
    (function (CategoriesEnum) {
        CategoriesEnum[CategoriesEnum["Hris"] = 'hris'] = "Hris";
        CategoriesEnum[CategoriesEnum["Ats"] = 'ats'] = "Ats";
        CategoriesEnum[CategoriesEnum["Accounting"] = 'accounting'] = "Accounting";
    })(CategoriesEnum = EndUserDetailsRequest.CategoriesEnum || (EndUserDetailsRequest.CategoriesEnum = {}));
})(EndUserDetailsRequest = exports.EndUserDetailsRequest || (exports.EndUserDetailsRequest = {}));
exports.EndUserDetailsRequest = EndUserDetailsRequest;
