"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.EthnicityEnum = void 0;
var EthnicityEnum;
(function (EthnicityEnum) {
    EthnicityEnum[EthnicityEnum["AmericanIndianOrAlaskaNative"] = 'AMERICAN_INDIAN_OR_ALASKA_NATIVE'] = "AmericanIndianOrAlaskaNative";
    EthnicityEnum[EthnicityEnum["AsianOrIndianSubcontinent"] = 'ASIAN_OR_INDIAN_SUBCONTINENT'] = "AsianOrIndianSubcontinent";
    EthnicityEnum[EthnicityEnum["BlackOrAfricanAmerican"] = 'BLACK_OR_AFRICAN_AMERICAN'] = "BlackOrAfricanAmerican";
    EthnicityEnum[EthnicityEnum["HispanicOrLatino"] = 'HISPANIC_OR_LATINO'] = "HispanicOrLatino";
    EthnicityEnum[EthnicityEnum["NativeHawaiianOrOtherPacificIslander"] = 'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER'] = "NativeHawaiianOrOtherPacificIslander";
    EthnicityEnum[EthnicityEnum["TwoOrMoreRaces"] = 'TWO_OR_MORE_RACES'] = "TwoOrMoreRaces";
    EthnicityEnum[EthnicityEnum["White"] = 'WHITE'] = "White";
    EthnicityEnum[EthnicityEnum["PreferNotToDisclose"] = 'PREFER_NOT_TO_DISCLOSE'] = "PreferNotToDisclose";
})(EthnicityEnum = exports.EthnicityEnum || (exports.EthnicityEnum = {}));
