"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.FlsaStatusEnum = void 0;
var FlsaStatusEnum;
(function (FlsaStatusEnum) {
    FlsaStatusEnum[FlsaStatusEnum["Exempt"] = 'EXEMPT'] = "Exempt";
    FlsaStatusEnum[FlsaStatusEnum["SalariedNonexempt"] = 'SALARIED_NONEXEMPT'] = "SalariedNonexempt";
    FlsaStatusEnum[FlsaStatusEnum["Nonexempt"] = 'NONEXEMPT'] = "Nonexempt";
    FlsaStatusEnum[FlsaStatusEnum["Owner"] = 'OWNER'] = "Owner";
})(FlsaStatusEnum = exports.FlsaStatusEnum || (exports.FlsaStatusEnum = {}));
