"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.GenderEnum = void 0;
var GenderEnum;
(function (GenderEnum) {
    GenderEnum[GenderEnum["Male"] = 'MALE'] = "Male";
    GenderEnum[GenderEnum["Female"] = 'FEMALE'] = "Female";
    GenderEnum[GenderEnum["NonBinary"] = 'NON-BINARY'] = "NonBinary";
    GenderEnum[GenderEnum["Other"] = 'OTHER'] = "Other";
    GenderEnum[GenderEnum["PreferNotToDisclose"] = 'PREFER_NOT_TO_DISCLOSE'] = "PreferNotToDisclose";
})(GenderEnum = exports.GenderEnum || (exports.GenderEnum = {}));
