"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.GenerateRemoteKeyRequest = void 0;
/**
* # The GenerateRemoteKey Object ### Description The `GenerateRemoteKey` object is used to represent a request for a new remote key.  ### Usage Example Post a `GenerateRemoteKey` to create a new remote key.
*/
var GenerateRemoteKeyRequest = /** @class */ (function () {
    function GenerateRemoteKeyRequest() {
    }
    GenerateRemoteKeyRequest.getAttributeTypeMap = function () {
        return GenerateRemoteKeyRequest.attributeTypeMap;
    };
    GenerateRemoteKeyRequest.discriminator = undefined;
    GenerateRemoteKeyRequest.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return GenerateRemoteKeyRequest;
}());
exports.GenerateRemoteKeyRequest = GenerateRemoteKeyRequest;
