"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.LinkToken = void 0;
var LinkToken = /** @class */ (function () {
    function LinkToken() {
    }
    LinkToken.getAttributeTypeMap = function () {
        return LinkToken.attributeTypeMap;
    };
    LinkToken.discriminator = undefined;
    LinkToken.attributeTypeMap = [
        {
            "name": "link_token",
            "baseName": "link_token",
            "type": "string"
        },
        {
            "name": "integration_name",
            "baseName": "integration_name",
            "type": "string"
        }
    ];
    return LinkToken;
}());
exports.LinkToken = LinkToken;
