"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.MaritalStatusEnum = void 0;
var MaritalStatusEnum;
(function (MaritalStatusEnum) {
    MaritalStatusEnum[MaritalStatusEnum["Single"] = 'SINGLE'] = "Single";
    MaritalStatusEnum[MaritalStatusEnum["MarriedFilingJointly"] = 'MARRIED_FILING_JOINTLY'] = "MarriedFilingJointly";
    MaritalStatusEnum[MaritalStatusEnum["MarriedFilingSeparately"] = 'MARRIED_FILING_SEPARATELY'] = "MarriedFilingSeparately";
    MaritalStatusEnum[MaritalStatusEnum["HeadOfHousehold"] = 'HEAD_OF_HOUSEHOLD'] = "HeadOfHousehold";
    MaritalStatusEnum[MaritalStatusEnum["QualifyingWidowOrWidowerWithDependentChild"] = 'QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD'] = "QualifyingWidowOrWidowerWithDependentChild";
})(MaritalStatusEnum = exports.MaritalStatusEnum || (exports.MaritalStatusEnum = {}));
