"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.MethodEnum = void 0;
var MethodEnum;
(function (MethodEnum) {
    MethodEnum[MethodEnum["Get"] = 'GET'] = "Get";
    MethodEnum[MethodEnum["Options"] = 'OPTIONS'] = "Options";
    MethodEnum[MethodEnum["Head"] = 'HEAD'] = "Head";
    MethodEnum[MethodEnum["Post"] = 'POST'] = "Post";
    MethodEnum[MethodEnum["Put"] = 'PUT'] = "Put";
    MethodEnum[MethodEnum["Patch"] = 'PATCH'] = "Patch";
    MethodEnum[MethodEnum["Delete"] = 'DELETE'] = "Delete";
})(MethodEnum = exports.MethodEnum || (exports.MethodEnum = {}));
