"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ModelOperation = void 0;
/**
* # The ModelOperation Object ### Description The `ModelOperation` object is used to represent the operations that are currently supported for a given model.  ### Usage Example View what operations are supported for the `Candidate` endpoint.
*/
var ModelOperation = /** @class */ (function () {
    function ModelOperation() {
    }
    ModelOperation.getAttributeTypeMap = function () {
        return ModelOperation.attributeTypeMap;
    };
    ModelOperation.discriminator = undefined;
    ModelOperation.attributeTypeMap = [
        {
            "name": "model_name",
            "baseName": "model_name",
            "type": "string"
        },
        {
            "name": "available_operations",
            "baseName": "available_operations",
            "type": "Array<string>"
        },
        {
            "name": "required_post_parameters",
            "baseName": "required_post_parameters",
            "type": "Array<string>"
        },
        {
            "name": "supported_fields",
            "baseName": "supported_fields",
            "type": "Array<string>"
        }
    ];
    return ModelOperation;
}());
exports.ModelOperation = ModelOperation;
