"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PaginatedPayrollRunList = void 0;
var PaginatedPayrollRunList = /** @class */ (function () {
    function PaginatedPayrollRunList() {
    }
    PaginatedPayrollRunList.getAttributeTypeMap = function () {
        return PaginatedPayrollRunList.attributeTypeMap;
    };
    PaginatedPayrollRunList.discriminator = undefined;
    PaginatedPayrollRunList.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<PayrollRun>"
        }
    ];
    return PaginatedPayrollRunList;
}());
exports.PaginatedPayrollRunList = PaginatedPayrollRunList;
