"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PaginatedLocationList = void 0;
var PaginatedLocationList = /** @class */ (function () {
    function PaginatedLocationList() {
    }
    PaginatedLocationList.getAttributeTypeMap = function () {
        return PaginatedLocationList.attributeTypeMap;
    };
    PaginatedLocationList.discriminator = undefined;
    PaginatedLocationList.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<Location>"
        }
    ];
    return PaginatedLocationList;
}());
exports.PaginatedLocationList = PaginatedLocationList;
