"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PaginatedSyncStatusList = void 0;
var PaginatedSyncStatusList = /** @class */ (function () {
    function PaginatedSyncStatusList() {
    }
    PaginatedSyncStatusList.getAttributeTypeMap = function () {
        return PaginatedSyncStatusList.attributeTypeMap;
    };
    PaginatedSyncStatusList.discriminator = undefined;
    PaginatedSyncStatusList.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SyncStatus>"
        }
    ];
    return PaginatedSyncStatusList;
}());
exports.PaginatedSyncStatusList = PaginatedSyncStatusList;
