"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PaginatedEmployeePayrollRunList = void 0;
var PaginatedEmployeePayrollRunList = /** @class */ (function () {
    function PaginatedEmployeePayrollRunList() {
    }
    PaginatedEmployeePayrollRunList.getAttributeTypeMap = function () {
        return PaginatedEmployeePayrollRunList.attributeTypeMap;
    };
    PaginatedEmployeePayrollRunList.discriminator = undefined;
    PaginatedEmployeePayrollRunList.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<EmployeePayrollRun>"
        }
    ];
    return PaginatedEmployeePayrollRunList;
}());
exports.PaginatedEmployeePayrollRunList = PaginatedEmployeePayrollRunList;
