"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PaginatedEmployeeList = void 0;
var PaginatedEmployeeList = /** @class */ (function () {
    function PaginatedEmployeeList() {
    }
    PaginatedEmployeeList.getAttributeTypeMap = function () {
        return PaginatedEmployeeList.attributeTypeMap;
    };
    PaginatedEmployeeList.discriminator = undefined;
    PaginatedEmployeeList.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<Employee>"
        }
    ];
    return PaginatedEmployeeList;
}());
exports.PaginatedEmployeeList = PaginatedEmployeeList;
