"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PaginatedTeamList = void 0;
var PaginatedTeamList = /** @class */ (function () {
    function PaginatedTeamList() {
    }
    PaginatedTeamList.getAttributeTypeMap = function () {
        return PaginatedTeamList.attributeTypeMap;
    };
    PaginatedTeamList.discriminator = undefined;
    PaginatedTeamList.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<Team>"
        }
    ];
    return PaginatedTeamList;
}());
exports.PaginatedTeamList = PaginatedTeamList;
