"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PayFrequencyEnum = void 0;
var PayFrequencyEnum;
(function (PayFrequencyEnum) {
    PayFrequencyEnum[PayFrequencyEnum["Weekly"] = 'WEEKLY'] = "Weekly";
    PayFrequencyEnum[PayFrequencyEnum["Biweekly"] = 'BIWEEKLY'] = "Biweekly";
    PayFrequencyEnum[PayFrequencyEnum["Monthly"] = 'MONTHLY'] = "Monthly";
    PayFrequencyEnum[PayFrequencyEnum["Quarterly"] = 'QUARTERLY'] = "Quarterly";
    PayFrequencyEnum[PayFrequencyEnum["Semiannually"] = 'SEMIANNUALLY'] = "Semiannually";
    PayFrequencyEnum[PayFrequencyEnum["Annually"] = 'ANNUALLY'] = "Annually";
    PayFrequencyEnum[PayFrequencyEnum["ThirteenMonthly"] = 'THIRTEEN-MONTHLY'] = "ThirteenMonthly";
    PayFrequencyEnum[PayFrequencyEnum["ProRata"] = 'PRO_RATA'] = "ProRata";
    PayFrequencyEnum[PayFrequencyEnum["Null"] = 'NULL'] = "Null";
})(PayFrequencyEnum = exports.PayFrequencyEnum || (exports.PayFrequencyEnum = {}));
