"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PayPeriodEnum = void 0;
var PayPeriodEnum;
(function (PayPeriodEnum) {
    PayPeriodEnum[PayPeriodEnum["Hour"] = 'HOUR'] = "Hour";
    PayPeriodEnum[PayPeriodEnum["Day"] = 'DAY'] = "Day";
    PayPeriodEnum[PayPeriodEnum["Week"] = 'WEEK'] = "Week";
    PayPeriodEnum[PayPeriodEnum["EveryTwoWeeks"] = 'EVERY_TWO_WEEKS'] = "EveryTwoWeeks";
    PayPeriodEnum[PayPeriodEnum["Month"] = 'MONTH'] = "Month";
    PayPeriodEnum[PayPeriodEnum["Quarter"] = 'QUARTER'] = "Quarter";
    PayPeriodEnum[PayPeriodEnum["EverySixMonths"] = 'EVERY_SIX_MONTHS'] = "EverySixMonths";
    PayPeriodEnum[PayPeriodEnum["Year"] = 'YEAR'] = "Year";
})(PayPeriodEnum = exports.PayPeriodEnum || (exports.PayPeriodEnum = {}));
