"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.PayrollRun = void 0;
/**
* # The PayrollRun Object ### Description The `PayrollRun` object is used to represent a payroll run.  ### Usage Example Fetch from the `LIST PayrollRuns` endpoint and filter by `ID` to show all payroll runs.
*/
var PayrollRun = /** @class */ (function () {
    function PayrollRun() {
    }
    PayrollRun.getAttributeTypeMap = function () {
        return PayrollRun.attributeTypeMap;
    };
    PayrollRun.discriminator = undefined;
    PayrollRun.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "run_state",
            "baseName": "run_state",
            "type": "RunStateEnum"
        },
        {
            "name": "run_type",
            "baseName": "run_type",
            "type": "RunTypeEnum"
        },
        {
            "name": "start_date",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "end_date",
            "baseName": "end_date",
            "type": "Date"
        },
        {
            "name": "check_date",
            "baseName": "check_date",
            "type": "Date"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        }
    ];
    return PayrollRun;
}());
exports.PayrollRun = PayrollRun;
