/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* # The PersistentDeduction Object ### Description The `PersistentDeduction` object is used to represent a deduction which persists across payroll runs  ### Usage Example Fetch from the `LIST PersistentDeductions` endpoint and filter by `employee_id` to show all persistent deductions for an employee.
*/
export class PersistentDeductionRequest {
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    /**
    * The deduction\'s employee.
    */
    'employee'?: string | null;
    /**
    * The deduction\'s calculation type.
    */
    'calculation_type'?: string | null;
    /**
    * The deduction\'s frequency.
    */
    'frequency'?: string | null;
    /**
    * The deduction\'s start date.
    */
    'effective_date'?: Date | null;
    /**
    * The deduction\'s end date.
    */
    'end_date'?: Date | null;
    /**
    * The amount the employee is deducting.
    */
    'amount_deducted'?: number | null;
    'remote_data'?: Array<{ [key: string]: any; }> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "employee",
            "baseName": "employee",
            "type": "string"
        },
        {
            "name": "calculation_type",
            "baseName": "calculation_type",
            "type": "string"
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "string"
        },
        {
            "name": "effective_date",
            "baseName": "effective_date",
            "type": "Date"
        },
        {
            "name": "end_date",
            "baseName": "end_date",
            "type": "Date"
        },
        {
            "name": "amount_deducted",
            "baseName": "amount_deducted",
            "type": "number"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<{ [key: string]: any; }>"
        }    ];

    static getAttributeTypeMap() {
        return PersistentDeductionRequest.attributeTypeMap;
    }
}

