"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RemoteKeyForRegenerationRequest = void 0;
/**
* # The RemoteKeyForRegeneration Object ### Description The `RemoteKeyForRegeneration` object is used to exchange an old remote key for a new one  ### Usage Example Post a `RemoteKeyForRegeneration` to swap out an old remote key for a new one
*/
var RemoteKeyForRegenerationRequest = /** @class */ (function () {
    function RemoteKeyForRegenerationRequest() {
    }
    RemoteKeyForRegenerationRequest.getAttributeTypeMap = function () {
        return RemoteKeyForRegenerationRequest.attributeTypeMap;
    };
    RemoteKeyForRegenerationRequest.discriminator = undefined;
    RemoteKeyForRegenerationRequest.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return RemoteKeyForRegenerationRequest;
}());
exports.RemoteKeyForRegenerationRequest = RemoteKeyForRegenerationRequest;
