"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RemoteResponse = void 0;
/**
* # The RemoteResponse Object ### Description The `RemoteResponse` object is used to represent information returned from a third-party endpoint.  ### Usage Example View the `RemoteResponse` returned from your `DataPassthrough`.
*/
var RemoteResponse = /** @class */ (function () {
    function RemoteResponse() {
    }
    RemoteResponse.getAttributeTypeMap = function () {
        return RemoteResponse.attributeTypeMap;
    };
    RemoteResponse.discriminator = undefined;
    RemoteResponse.attributeTypeMap = [
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: any; }"
        }
    ];
    return RemoteResponse;
}());
exports.RemoteResponse = RemoteResponse;
