"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RemoteKey = void 0;
/**
* # The RemoteKey Object ### Description The `RemoteKey` object is used to represent a request for a new remote key.  ### Usage Example Post a `GenerateRemoteKey` to receive a new `RemoteKey`.
*/
var RemoteKey = /** @class */ (function () {
    function RemoteKey() {
    }
    RemoteKey.getAttributeTypeMap = function () {
        return RemoteKey.attributeTypeMap;
    };
    RemoteKey.discriminator = undefined;
    RemoteKey.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        }
    ];
    return RemoteKey;
}());
exports.RemoteKey = RemoteKey;
