"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RemoteDataRequest = void 0;
var RemoteDataRequest = /** @class */ (function () {
    function RemoteDataRequest() {
    }
    RemoteDataRequest.getAttributeTypeMap = function () {
        return RemoteDataRequest.attributeTypeMap;
    };
    RemoteDataRequest.discriminator = undefined;
    RemoteDataRequest.attributeTypeMap = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }"
        }
    ];
    return RemoteDataRequest;
}());
exports.RemoteDataRequest = RemoteDataRequest;
