"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RequestTypeEnum = void 0;
var RequestTypeEnum;
(function (RequestTypeEnum) {
    RequestTypeEnum[RequestTypeEnum["Vacation"] = 'VACATION'] = "Vacation";
    RequestTypeEnum[RequestTypeEnum["Sick"] = 'SICK'] = "Sick";
    RequestTypeEnum[RequestTypeEnum["Personal"] = 'PERSONAL'] = "Personal";
    RequestTypeEnum[RequestTypeEnum["JuryDuty"] = 'JURY_DUTY'] = "JuryDuty";
})(RequestTypeEnum = exports.RequestTypeEnum || (exports.RequestTypeEnum = {}));
