"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RunStateEnum = void 0;
var RunStateEnum;
(function (RunStateEnum) {
    RunStateEnum[RunStateEnum["Paid"] = 'PAID'] = "Paid";
    RunStateEnum[RunStateEnum["Draft"] = 'DRAFT'] = "Draft";
    RunStateEnum[RunStateEnum["Approved"] = 'APPROVED'] = "Approved";
    RunStateEnum[RunStateEnum["Failed"] = 'FAILED'] = "Failed";
    RunStateEnum[RunStateEnum["Closed"] = 'CLOSED'] = "Closed";
})(RunStateEnum = exports.RunStateEnum || (exports.RunStateEnum = {}));
