/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum RunTypeEnum {
    Init = <any> 'INIT',
    Regular = <any> 'REGULAR',
    OffCycle = <any> 'OFF_CYCLE',
    Correction = <any> 'CORRECTION',
    Termination = <any> 'TERMINATION',
    Reconciliation = <any> 'RECONCILIATION',
    NewHire = <any> 'NEW_HIRE',
    Pop = <any> 'POP',
    Transition = <any> 'TRANSITION',
    CorrectionDisplay = <any> 'CORRECTION_DISPLAY',
    ExcessHours = <any> 'EXCESS_HOURS',
    SignOnBonus = <any> 'SIGN_ON_BONUS',
    SCorp = <any> 'S_CORP',
    FringeBenefits = <any> 'FRINGE_BENEFITS',
    ContractorLatePayments = <any> 'CONTRACTOR_LATE_PAYMENTS'
}
