"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.RunTypeEnum = void 0;
var RunTypeEnum;
(function (RunTypeEnum) {
    RunTypeEnum[RunTypeEnum["Init"] = 'INIT'] = "Init";
    RunTypeEnum[RunTypeEnum["Regular"] = 'REGULAR'] = "Regular";
    RunTypeEnum[RunTypeEnum["OffCycle"] = 'OFF_CYCLE'] = "OffCycle";
    RunTypeEnum[RunTypeEnum["Correction"] = 'CORRECTION'] = "Correction";
    RunTypeEnum[RunTypeEnum["Termination"] = 'TERMINATION'] = "Termination";
    RunTypeEnum[RunTypeEnum["Reconciliation"] = 'RECONCILIATION'] = "Reconciliation";
    RunTypeEnum[RunTypeEnum["NewHire"] = 'NEW_HIRE'] = "NewHire";
    RunTypeEnum[RunTypeEnum["Pop"] = 'POP'] = "Pop";
    RunTypeEnum[RunTypeEnum["Transition"] = 'TRANSITION'] = "Transition";
    RunTypeEnum[RunTypeEnum["CorrectionDisplay"] = 'CORRECTION_DISPLAY'] = "CorrectionDisplay";
    RunTypeEnum[RunTypeEnum["ExcessHours"] = 'EXCESS_HOURS'] = "ExcessHours";
    RunTypeEnum[RunTypeEnum["SignOnBonus"] = 'SIGN_ON_BONUS'] = "SignOnBonus";
    RunTypeEnum[RunTypeEnum["SCorp"] = 'S_CORP'] = "SCorp";
    RunTypeEnum[RunTypeEnum["FringeBenefits"] = 'FRINGE_BENEFITS'] = "FringeBenefits";
    RunTypeEnum[RunTypeEnum["ContractorLatePayments"] = 'CONTRACTOR_LATE_PAYMENTS'] = "ContractorLatePayments";
})(RunTypeEnum = exports.RunTypeEnum || (exports.RunTypeEnum = {}));
