"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SyncStatus = void 0;
/**
* # The SyncStatus Object ### Description The `SyncStatus` object is used to represent the syncing state of an account  ### Usage Example View the `SyncStatus` for an account to see how recently its models were synced.
*/
var SyncStatus = /** @class */ (function () {
    function SyncStatus() {
    }
    SyncStatus.getAttributeTypeMap = function () {
        return SyncStatus.attributeTypeMap;
    };
    SyncStatus.discriminator = undefined;
    SyncStatus.attributeTypeMap = [
        {
            "name": "model_name",
            "baseName": "model_name",
            "type": "string"
        },
        {
            "name": "model_id",
            "baseName": "model_id",
            "type": "string"
        },
        {
            "name": "last_sync_start",
            "baseName": "last_sync_start",
            "type": "Date"
        },
        {
            "name": "next_sync_start",
            "baseName": "next_sync_start",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SyncStatusStatusEnum"
        },
        {
            "name": "is_initial_sync",
            "baseName": "is_initial_sync",
            "type": "boolean"
        }
    ];
    return SyncStatus;
}());
exports.SyncStatus = SyncStatus;
