"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SyncStatusStatusEnum = void 0;
var SyncStatusStatusEnum;
(function (SyncStatusStatusEnum) {
    SyncStatusStatusEnum[SyncStatusStatusEnum["Syncing"] = 'SYNCING'] = "Syncing";
    SyncStatusStatusEnum[SyncStatusStatusEnum["Done"] = 'DONE'] = "Done";
})(SyncStatusStatusEnum = exports.SyncStatusStatusEnum || (exports.SyncStatusStatusEnum = {}));
