/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* # The Tax Object ### Description The `Tax` object is used to represent a tax for a given employee\'s payroll run. One run could include several taxes.  ### Usage Example Fetch from the `LIST Taxes` endpoint and filter by `ID` to show all taxes.
*/
export class Tax {
    'id'?: string;
    /**
    * The tax\'s employee payroll run.
    */
    'employeePayrollRun'?: string | null;
    /**
    * The tax\'s name.
    */
    'name'?: string | null;
    /**
    * The tax amount.
    */
    'amount'?: number | null;
    /**
    * Whether or not the employer is responsible for paying the tax.
    */
    'employerTax'?: boolean | null;
    'remoteData'?: Array<{ [key: string]: any; }> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "employeePayrollRun",
            "baseName": "employee_payroll_run",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "employerTax",
            "baseName": "employer_tax",
            "type": "boolean"
        },
        {
            "name": "remoteData",
            "baseName": "remote_data",
            "type": "Array<{ [key: string]: any; }>"
        }    ];

    static getAttributeTypeMap() {
        return Tax.attributeTypeMap;
    }
}

