/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorValidationProblem } from './errorValidationProblem';
import { TimeOff } from './timeOff';
import { WarningValidationProblem } from './warningValidationProblem';

export class TimeOffResponse {
    'model': TimeOff;
    'warnings': Array<WarningValidationProblem>;
    'errors': Array<ErrorValidationProblem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "model",
            "baseName": "model",
            "type": "TimeOff"
        },
        {
            "name": "warnings",
            "baseName": "warnings",
            "type": "Array<WarningValidationProblem>"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ErrorValidationProblem>"
        }    ];

    static getAttributeTypeMap() {
        return TimeOffResponse.attributeTypeMap;
    }
}

