"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.TimeOffStatusEnum = void 0;
var TimeOffStatusEnum;
(function (TimeOffStatusEnum) {
    TimeOffStatusEnum[TimeOffStatusEnum["Requested"] = 'REQUESTED'] = "Requested";
    TimeOffStatusEnum[TimeOffStatusEnum["Approved"] = 'APPROVED'] = "Approved";
    TimeOffStatusEnum[TimeOffStatusEnum["Declined"] = 'DECLINED'] = "Declined";
    TimeOffStatusEnum[TimeOffStatusEnum["Cancelled"] = 'CANCELLED'] = "Cancelled";
    TimeOffStatusEnum[TimeOffStatusEnum["Deleted"] = 'DELETED'] = "Deleted";
})(TimeOffStatusEnum = exports.TimeOffStatusEnum || (exports.TimeOffStatusEnum = {}));
