"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.TypeEnum = void 0;
var TypeEnum;
(function (TypeEnum) {
    TypeEnum[TypeEnum["Salary"] = 'SALARY'] = "Salary";
    TypeEnum[TypeEnum["Reimbursement"] = 'REIMBURSEMENT'] = "Reimbursement";
    TypeEnum[TypeEnum["Overtime"] = 'OVERTIME'] = "Overtime";
    TypeEnum[TypeEnum["Bonus"] = 'BONUS'] = "Bonus";
})(TypeEnum = exports.TypeEnum || (exports.TypeEnum = {}));
