"use strict";
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.UnitsEnum = void 0;
var UnitsEnum;
(function (UnitsEnum) {
    UnitsEnum[UnitsEnum["Hours"] = 'HOURS'] = "Hours";
    UnitsEnum[UnitsEnum["Days"] = 'DAYS'] = "Days";
})(UnitsEnum = exports.UnitsEnum || (exports.UnitsEnum = {}));
