/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { PaginatedTimeOffList } from '../model/paginatedTimeOffList';
import { TimeOff } from '../model/timeOff';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.merge.dev/api/hris/v1';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum TimeOffApiApiKeys {
    tokenAuth,
}

export class TimeOffApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'tokenAuth': new ApiKeyAuth('header', 'Authorization'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: TimeOffApiApiKeys, value: string) {
        (this.authentications as any)[TimeOffApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Creates a `TimeOff` object with the given values.
     * @param x_account_token Token identifying the end user.
     * @param run_async Whether or not third-party updates should be run asynchronously.
     * @param time_off 
     */
    public async timeOffCreate (x_account_token: string, run_async?: boolean, time_off?: TimeOff, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: TimeOff;  }> {
        const localVarPath = this.basePath + '/time-off';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'x_account_token' is not null or undefined
        if (x_account_token === null || x_account_token === undefined) {
            throw new Error('Required parameter x_account_token was null or undefined when calling timeOffCreate.');
        }

        if (run_async !== undefined) {
            localVarQueryParameters['run_async'] = ObjectSerializer.serialize(run_async, "boolean");
        }

        localVarHeaderParams['X-Account-Token'] = ObjectSerializer.serialize(x_account_token, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(time_off, "TimeOff")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.tokenAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.tokenAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: TimeOff;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        body = ObjectSerializer.deserialize(body, "TimeOff");
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns a list of `TimeOff` objects.
     * @param x_account_token Token identifying the end user.
     * @param approver_id If provided, will only return time off for this approver.
     * @param created_after If provided, will only return objects created after this datetime.
     * @param created_before If provided, will only return objects created before this datetime.
     * @param cursor The pagination cursor value.
     * @param employee_id If provided, will only return time off for this employee.
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
     * @param include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
     * @param modified_after If provided, will only return objects modified after this datetime.
     * @param modified_before If provided, will only return objects modified before this datetime.
     * @param page_size Number of results to return per page.
     * @param remote_id The API provider\&#39;s ID for the given object.
     * @param request_type If provided, will only return TimeOff with this request type. Options: (\&#39;VACATION\&#39;, \&#39;SICK\&#39;, \&#39;PERSONAL\&#39;, \&#39;JURY_DUTY\&#39;, \&#39;VOLUNTEER\&#39;, \&#39;BEREAVEMENT\&#39;)
     * @param status If provided, will only return TimeOff with this status. Options: (\&#39;REQUESTED\&#39;, \&#39;APPROVED\&#39;, \&#39;DECLINED\&#39;, \&#39;CANCELLED\&#39;, \&#39;DELETED\&#39;)
     */
    public async timeOffList (x_account_token: string, approver_id?: string, created_after?: Date, created_before?: Date, cursor?: string, employee_id?: string, expand?: 'approver' | 'employee' | 'employee,approver', include_remote_data?: boolean, modified_after?: Date, modified_before?: Date, page_size?: number, remote_id?: string, request_type?: '' | 'BEREAVEMENT' | 'JURY_DUTY' | 'null' | 'PERSONAL' | 'SICK' | 'VACATION' | 'VOLUNTEER', status?: '' | 'APPROVED' | 'CANCELLED' | 'DECLINED' | 'DELETED' | 'null' | 'REQUESTED', options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: PaginatedTimeOffList;  }> {
        const localVarPath = this.basePath + '/time-off';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'x_account_token' is not null or undefined
        if (x_account_token === null || x_account_token === undefined) {
            throw new Error('Required parameter x_account_token was null or undefined when calling timeOffList.');
        }

        if (approver_id !== undefined) {
            localVarQueryParameters['approver_id'] = ObjectSerializer.serialize(approver_id, "string");
        }

        if (created_after !== undefined) {
            localVarQueryParameters['created_after'] = ObjectSerializer.serialize(created_after, "Date");
        }

        if (created_before !== undefined) {
            localVarQueryParameters['created_before'] = ObjectSerializer.serialize(created_before, "Date");
        }

        if (cursor !== undefined) {
            localVarQueryParameters['cursor'] = ObjectSerializer.serialize(cursor, "string");
        }

        if (employee_id !== undefined) {
            localVarQueryParameters['employee_id'] = ObjectSerializer.serialize(employee_id, "string");
        }

        if (expand !== undefined) {
            localVarQueryParameters['expand'] = ObjectSerializer.serialize(expand, "'approver' | 'employee' | 'employee,approver'");
        }

        if (include_remote_data !== undefined) {
            localVarQueryParameters['include_remote_data'] = ObjectSerializer.serialize(include_remote_data, "boolean");
        }

        if (modified_after !== undefined) {
            localVarQueryParameters['modified_after'] = ObjectSerializer.serialize(modified_after, "Date");
        }

        if (modified_before !== undefined) {
            localVarQueryParameters['modified_before'] = ObjectSerializer.serialize(modified_before, "Date");
        }

        if (page_size !== undefined) {
            localVarQueryParameters['page_size'] = ObjectSerializer.serialize(page_size, "number");
        }

        if (remote_id !== undefined) {
            localVarQueryParameters['remote_id'] = ObjectSerializer.serialize(remote_id, "string");
        }

        if (request_type !== undefined) {
            localVarQueryParameters['request_type'] = ObjectSerializer.serialize(request_type, "'' | 'BEREAVEMENT' | 'JURY_DUTY' | 'null' | 'PERSONAL' | 'SICK' | 'VACATION' | 'VOLUNTEER'");
        }

        if (status !== undefined) {
            localVarQueryParameters['status'] = ObjectSerializer.serialize(status, "'' | 'APPROVED' | 'CANCELLED' | 'DECLINED' | 'DELETED' | 'null' | 'REQUESTED'");
        }

        localVarHeaderParams['X-Account-Token'] = ObjectSerializer.serialize(x_account_token, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.tokenAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.tokenAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: PaginatedTimeOffList;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        body = ObjectSerializer.deserialize(body, "PaginatedTimeOffList");
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns a `TimeOff` object with the given `id`.
     * @param x_account_token Token identifying the end user.
     * @param id 
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
     * @param include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
     */
    public async timeOffRetrieve (x_account_token: string, id: string, expand?: 'approver' | 'employee' | 'employee,approver', include_remote_data?: boolean, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: TimeOff;  }> {
        const localVarPath = this.basePath + '/time-off/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'x_account_token' is not null or undefined
        if (x_account_token === null || x_account_token === undefined) {
            throw new Error('Required parameter x_account_token was null or undefined when calling timeOffRetrieve.');
        }

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling timeOffRetrieve.');
        }

        if (expand !== undefined) {
            localVarQueryParameters['expand'] = ObjectSerializer.serialize(expand, "'approver' | 'employee' | 'employee,approver'");
        }

        if (include_remote_data !== undefined) {
            localVarQueryParameters['include_remote_data'] = ObjectSerializer.serialize(include_remote_data, "boolean");
        }

        localVarHeaderParams['X-Account-Token'] = ObjectSerializer.serialize(x_account_token, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.tokenAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.tokenAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: TimeOff;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        body = ObjectSerializer.deserialize(body, "TimeOff");
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
